# Generated by Django 3.0.3 on 2020-02-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(height_field=100, upload_to=None, width_field=200),
        ),
    ]
