# Generated by Django 3.0.3 on 2020-02-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0002_auto_20200216_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
    ]
